services:

  payment-service:
    image: payment-service:1.0

    build:
      context: .
      dockerfile: Dockerfile

    container_name: payment-service

    restart: unless-stopped

    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}

      SERVER_PORT: ${SERVER_PORT}

      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}

      RANDOM_API_URL: ${RANDOM_API_URL}

      GATEWAY_API_KEY: ${GATEWAY_API_KEY}

      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}

    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy

    networks:
      - payment-service-network
      - kafka-network


  mongodb:
    image: mongodb/mongodb-community-server:8.3.4-ubi9

    container_name: payment-service-mongo

    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

    ports:
      - "${MONGO_HOST_PORT}:${MONGO_PORT}"

    command: mongod --port ${MONGO_PORT}

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --port ${MONGO_PORT} --quiet
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

    volumes:
      - mongo-data:/data/db

    networks:
      - payment-service-network


  kafka:
    image: apache/kafka:4.3.1

    container_name: payment-service-kafka

    restart: unless-stopped

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${KAFKA_HOST}:${KAFKA_PORT},EXTERNAL://localhost:${KAFKA_HOST_PORT}
      KAFKA_LISTENERS: CONTROLLER://${KAFKA_HOST}:${KAFKA_CONTROLLER_PORT},INTERNAL://${KAFKA_HOST}:${KAFKA_PORT},EXTERNAL://0.0.0.0:${KAFKA_HOST_PORT}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${KAFKA_HOST}:${KAFKA_CONTROLLER_PORT}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    ports:
      - "${KAFKA_HOST_PORT}:${KAFKA_HOST_PORT}"

    healthcheck:
      test: [ "CMD-SHELL", "ps aux | grep -v grep | grep kafka || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

    volumes:
      - kafka-data:/var/lib/kafka/data

    networks:
      - kafka-network


volumes:
  mongo-data:
  kafka-data:


networks:
  payment-service-network:
    driver: bridge
    name: payment-service-network
  kafka-network:
    driver: bridge
    name: kafka-network