server.port=${SERVER_PORT}

spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin

spring.kafka.bootstrap-servers=localhost:${KAFKA_PORT}

payment.random-api.url=${RANDOM_API_URL}