spring.application.name=payment-service

spring.config.import=optional:file:.env[.properties]

spring.profiles.active=${ACTIVE_PROFILE}

gateway.api-key=${GATEWAY_API_KEY}

mongock.migration-scan-package=com.innowise.paymentservice.migration

spring.data.mongodb.auto-index-creation=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.innowise.paymentservice.kafka.event.CreateOrderEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.version=@project.version@
info.app.java=${java.version}

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.innowise=TRACE