spring.application.name=payment-service

spring.config.import=optional:file:.env[.properties]

spring.profiles.active=${ACTIVE_PROFILE}

internal.api-key=${INTERNAL_API_KEY}

mongock.migration-scan-package=com.innowise.paymentservice.migration

spring.data.mongodb.auto-index-creation=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

logging.level.org.springframework.data.mongodb=INFO
logging.level.org.apache.kafka=INFO