spring.application.name=payment-service

spring.config.import=optional:file:.env[.properties]

spring.profiles.active=${ACTIVE_PROFILE}

mongock.migration-scan-package=com.innowise.paymentservice.migration

spring.data.mongodb.auto-index-creation=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.spring.json.add.type.headers=false

logging.level.org.springframework.data.mongodb=INFO
logging.level.org.apache.kafka=INFO